# Generated by Django 4.1.2 on 2022-10-07 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analista",
            fields=[
                (
                    "analista_id",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BarreraAcceso",
            fields=[
                (
                    "id_barrera_acceso",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Casos",
            fields=[
                (
                    "id_caso",
                    models.AutoField(
                        db_column="id_caso", primary_key=True, serialize=False
                    ),
                ),
                (
                    "numeroradicado",
                    models.PositiveIntegerField(db_column="numeroRadicado"),
                ),
                (
                    "fechaatencioneps",
                    models.DateTimeField(db_column="fechaAtencionEps"),
                ),
                ("descripcioncaso", models.TextField(db_column="descripcionCaso")),
                ("agregardocum", models.FileField(upload_to="uploads/% Y/% m/% d/")),
                (
                    "fecharesgistrocaso",
                    models.DateTimeField(
                        blank=True, db_column="fechaResgistroCaso", null=True
                    ),
                ),
                (
                    "fechaatenproceso",
                    models.DateTimeField(db_column="fechaAtenProceso", null=True),
                ),
                (
                    "fechaatenfinalizado",
                    models.DateTimeField(db_column="fechaAtenFinalizado", null=True),
                ),
                (
                    "fechaatenabierto",
                    models.DateTimeField(db_column="fechaAtenAbierto", null=True),
                ),
                ("hora", models.TimeField(null=True)),
                ("formula_medica", models.FileField(upload_to="specs")),
                ("adjunto_pri", models.FileField(upload_to="uploads/% Y/% m/% d/")),
                ("adjunto_seg", models.FileField(upload_to="uploads/% Y/% m/% d/")),
                ("adjunto_terc", models.FileField(upload_to="uploads/% Y/% m/% d/")),
            ],
        ),
        migrations.CreateModel(
            name="ClasificacionPbs",
            fields=[
                ("id_pbs", models.IntegerField(primary_key=True, serialize=False)),
                ("nombrepbs", models.CharField(db_column="nombrePbs", max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="DatosUsuario",
            fields=[
                (
                    "id_cedula",
                    models.PositiveIntegerField(
                        db_column="id_cedula", primary_key=True, serialize=False
                    ),
                ),
                (
                    "primer_nombre",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "primer_apellido",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "segundo_nombre",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("celular", models.BigIntegerField(blank=True, null=True)),
                ("direccion", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "fechanaci",
                    models.DateField(blank=True, db_column="fechaNaci", null=True),
                ),
                ("ocupacion", models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "cod_dep",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnvioAlertas",
            fields=[
                ("tipoenvio", models.CharField(db_column="tipoEnvio", max_length=40)),
                ("id_envio", models.SmallAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Eps",
            fields=[
                ("cod_eps", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EspecialidadMed",
            fields=[
                ("id_esp", models.SmallAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "idestado",
                    models.AutoField(
                        db_column="idEstado", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nombreestado",
                    models.CharField(db_column="nombreEstado", max_length=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "idgenero",
                    models.PositiveIntegerField(
                        db_column="idGenero", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nombregenero",
                    models.CharField(db_column="nombreGenero", max_length=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GestorCaso",
            fields=[
                (
                    "id_gest",
                    models.SmallAutoField(
                        db_column="Id_gest", primary_key=True, serialize=False
                    ),
                ),
                (
                    "cantcasos",
                    models.SmallIntegerField(
                        blank=True, db_column="cantCasos", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GestorFarmacia",
            fields=[
                (
                    "id_far",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "nombrefarmacia",
                    models.CharField(db_column="nombreFarmacia", max_length=40),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrupoEtnico",
            fields=[
                (
                    "id_gr_etn",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "nombreetnico",
                    models.CharField(db_column="nombreEtnico", max_length=40),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ips",
            fields=[
                ("id_terapia", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="MensajesCorreo",
            fields=[
                ("id_correo", models.SmallAutoField(primary_key=True, serialize=False)),
                ("recibido", models.TextField(blank=True, null=True)),
                ("enviados", models.CharField(blank=True, max_length=40, null=True)),
                ("asunto", models.CharField(blank=True, max_length=50, null=True)),
                ("mensaje", models.TextField(blank=True, null=True)),
                ("adjunto", models.FileField(upload_to="uploads/% Y/% m/% d/")),
            ],
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "cod_municipio",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "nombremunicipio",
                    models.CharField(
                        blank=True,
                        db_column="nombreMunicipio",
                        max_length=15,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("cod_pais", models.SmallAutoField(primary_key=True, serialize=False)),
                ("nombrepais", models.CharField(db_column="nombrePais", max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="PoblacionEspecial",
            fields=[
                (
                    "id_pb_esp",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "nombrepoblacionesp",
                    models.CharField(
                        blank=True,
                        db_column="nombrePoblacionEsp",
                        max_length=40,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Regimen",
            fields=[
                (
                    "cod_regimen",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "nombreregimen",
                    models.CharField(db_column="nombreRegimen", max_length=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Terapia",
            fields=[
                (
                    "id_terapia",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "nombreterapia",
                    models.CharField(db_column="nombreTerapia", max_length=40),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                ("id_doc", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombredocumento",
                    models.CharField(db_column="nombreDocumento", max_length=40),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoEnfermedad",
            fields=[
                (
                    "id_enfermedad",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                (
                    "nombreenfermedad",
                    models.CharField(db_column="nombreEnfermedad", max_length=40),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipReq",
            fields=[
                (
                    "id_req",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "nombrerequerimiento",
                    models.CharField(db_column="nombreRequerimiento", max_length=40),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisualizacionCasoHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_caso", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.datosusuario",
                    ),
                ),
                (
                    "idcaso",
                    models.ForeignKey(
                        db_column="idCaso",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.casos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                ("id_seg", models.SmallAutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField()),
                (
                    "id_gestor",
                    models.ForeignKey(
                        db_column="id_gestor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.gestorcaso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reportes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporte", models.FileField(upload_to="uploads/% Y/% m/% d/")),
                (
                    "id_caso",
                    models.ForeignKey(
                        db_column="id_caso",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.casos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PacienteUsuario",
            fields=[
                (
                    "id_paciente",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                (
                    "numusu",
                    models.SmallIntegerField(blank=True, db_column="numUsu", null=True),
                ),
                (
                    "id_correo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_correo",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.mensajescorreo",
                    ),
                ),
                (
                    "id_dat_us",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_dat_us",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.datosusuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfoComplementaria",
            fields=[
                ("id_comple", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "otra_terapia",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "clasificacion_pbs",
                    models.SmallIntegerField(blank=True, null=True, unique=True),
                ),
                ("medico_trat", models.CharField(max_length=40)),
                ("segunda_barrera", models.CharField(max_length=40)),
                ("barrera_acceso", models.CharField(max_length=40)),
                (
                    "fech_rad_for_eps",
                    models.DateTimeField(db_column="fech_rad_for_EPS"),
                ),
                ("fecha_for_medi", models.DateTimeField()),
                ("fecha_aut", models.DateTimeField()),
                ("fech_rad_aut_farm", models.DateTimeField()),
                ("fecha_entrega", models.DateTimeField()),
                ("origen_soli", models.CharField(max_length=40)),
                (
                    "especialidad_med",
                    models.ForeignKey(
                        db_column="especialidad_med",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.especialidadmed",
                    ),
                ),
                (
                    "gestor_farma",
                    models.ForeignKey(
                        db_column="gestor_farma",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.gestorfarmacia",
                    ),
                ),
                (
                    "ips_id_terapia",
                    models.ForeignKey(
                        db_column="ips_id_terapia",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.ips",
                    ),
                ),
                (
                    "terapia",
                    models.ForeignKey(
                        db_column="terapia",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.terapia",
                    ),
                ),
                (
                    "tipo_req",
                    models.ForeignKey(
                        blank=True,
                        db_column="tipo_req",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.tipreq",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicadoresGestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_ind_ges", models.PositiveSmallIntegerField()),
                (
                    "tiempores",
                    models.DateField(blank=True, db_column="tiempoRes", null=True),
                ),
                (
                    "resolutividad",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "idusuario",
                    models.ForeignKey(
                        db_column="idUsuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.datosusuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gestorcaso",
            name="id_correo",
            field=models.ForeignKey(
                blank=True,
                db_column="id_correo",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.mensajescorreo",
            ),
        ),
        migrations.AddField(
            model_name="gestorcaso",
            name="id_datos_us",
            field=models.ForeignKey(
                blank=True,
                db_column="id_datos_us",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.datosusuario",
            ),
        ),
        migrations.CreateModel(
            name="Enuesta",
            fields=[
                (
                    "idencuesta",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                (
                    "evaluacionres",
                    models.CharField(
                        blank=True, db_column="evaluacionRes", max_length=40, null=True
                    ),
                ),
                (
                    "evaliaciongestor",
                    models.IntegerField(
                        blank=True, db_column="evaliacionGestor", null=True
                    ),
                ),
                (
                    "idusuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="idUsuario",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.datosusuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="cod_dep",
            field=models.ForeignKey(
                db_column="cod_dep",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.departamento",
            ),
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="cod_muni",
            field=models.ForeignKey(
                db_column="cod_muni",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.municipio",
            ),
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="cod_pais",
            field=models.ForeignKey(
                db_column="cod_pais",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.pais",
            ),
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="id_eps",
            field=models.ForeignKey(
                db_column="id_EPS",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.eps",
            ),
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="id_grupo_etnico",
            field=models.ForeignKey(
                db_column="id_grupo_etnico",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.grupoetnico",
            ),
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="id_poblacion_especial",
            field=models.ForeignKey(
                db_column="id_poblacion_especial",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.poblacionespecial",
            ),
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="idgenero",
            field=models.ForeignKey(
                blank=True,
                db_column="idGenero",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.genero",
            ),
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="idtiporegimen",
            field=models.ForeignKey(
                db_column="IdTipoRegimen",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.regimen",
            ),
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="login_id",
            field=models.OneToOneField(
                db_column="login_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="tipo_doc",
            field=models.ForeignKey(
                db_column="tipo_doc",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.tipodocumento",
            ),
        ),
        migrations.AddField(
            model_name="datosusuario",
            name="tipo_envio",
            field=models.ForeignKey(
                db_column="tipo_envio",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.envioalertas",
            ),
        ),
        migrations.CreateModel(
            name="DatosAnalisis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("informe", models.SmallIntegerField(blank=True, null=True)),
                (
                    "id_analista",
                    models.ForeignKey(
                        db_column="id_analista",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.analista",
                    ),
                ),
                (
                    "id_caso",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_caso",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.casos",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="casos",
            name="enfermedad",
            field=models.ForeignKey(
                blank=True,
                db_column="enfermedad",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.tipoenfermedad",
            ),
        ),
        migrations.AddField(
            model_name="casos",
            name="estado",
            field=models.ForeignKey(
                db_column="estado",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.estado",
            ),
        ),
        migrations.AddField(
            model_name="casos",
            name="id_barrera",
            field=models.ForeignKey(
                db_column="id_barrera",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.barreraacceso",
            ),
        ),
        migrations.AddField(
            model_name="casos",
            name="id_comple_info",
            field=models.ForeignKey(
                blank=True,
                db_column="id_comple_info",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.infocomplementaria",
            ),
        ),
        migrations.AddField(
            model_name="casos",
            name="id_gest",
            field=models.ForeignKey(
                db_column="id_gest",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.gestorcaso",
            ),
        ),
        migrations.AddField(
            model_name="casos",
            name="id_seguimiento",
            field=models.ForeignKey(
                db_column="id_seguimiento",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.seguimiento",
            ),
        ),
        migrations.AddField(
            model_name="casos",
            name="id_usuario",
            field=models.ForeignKey(
                db_column="id_usuario",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.datosusuario",
            ),
        ),
        migrations.CreateModel(
            name="AsignacionTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actividad", models.CharField(max_length=40)),
                ("fecha", models.DateTimeField()),
                ("fech_registro", models.DateField()),
                (
                    "id_gest",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_gest",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.gestorcaso",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="analista",
            name="id_correo",
            field=models.ForeignKey(
                db_column="id_correo",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.mensajescorreo",
            ),
        ),
        migrations.AddField(
            model_name="analista",
            name="id_datos_us",
            field=models.ForeignKey(
                db_column="id_datos_us",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.datosusuario",
            ),
        ),
    ]
