# Generated by Django 4.1.2 on 2022-10-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casos",
            name="estado_pendiente",
            field=models.CharField(
                choices=[("True", "True"), ("False", "False")],
                default="True",
                max_length=8,
            ),
        ),
    ]
