# Generated by Django 4.1.2 on 2022-10-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_casos_estado_pendiente"),
    ]

    operations = [
        migrations.RemoveField(model_name="casos", name="adjunto_pri",),
        migrations.RemoveField(model_name="casos", name="agregardocum",),
        migrations.AlterField(
            model_name="casos",
            name="adjunto_seg",
            field=models.FileField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="casos",
            name="adjunto_terc",
            field=models.FileField(upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="casos",
            name="formula_medica",
            field=models.FileField(upload_to="media/"),
        ),
    ]
