# Generated by Django 4.1.2 on 2022-10-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_casos_adjunto_pri_remove_casos_agregardocum_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="infocomplementaria", name="barrera_acceso",),
        migrations.AlterField(
            model_name="casos",
            name="adjunto_seg",
            field=models.FileField(upload_to="%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="casos",
            name="adjunto_terc",
            field=models.FileField(upload_to="%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="casos",
            name="formula_medica",
            field=models.FileField(upload_to="%Y/%m/%d/"),
        ),
    ]
