# Generated by Django 4.1.2 on 2022-10-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_infocomplementaria_barrera_acceso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clasificacionpbs",
            name="id_pbs",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
