# Generated by Django 4.1.2 on 2022-10-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_clasificacionpbs_id_pbs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clasificacionpbs",
            name="nombrepbs",
            field=models.CharField(db_column="nombrePbs", max_length=60),
        ),
    ]
