# Generated by Django 4.1.2 on 2022-10-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_clasificacionpbs_nombrepbs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipreq",
            name="id_req",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
