# Generated by Django 4.1.2 on 2022-10-19 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_tipreq_id_req"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infocomplementaria",
            name="clasificacion_pbs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.clasificacionpbs",
            ),
        ),
    ]
