# Generated by Django 4.1.2 on 2022-10-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_terapia_id_terapia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestorfarmacia",
            name="id_far",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
