# Generated by Django 4.1.2 on 2022-10-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_casos_estado_pendiente"),
    ]

    operations = [
        migrations.AddField(
            model_name="seguimiento",
            name="fecharegistro",
            field=models.DateField(blank=True, db_column="fechare", null=True),
        ),
    ]
