# Generated by Django 4.1.2 on 2022-10-23 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_seguimiento_fecharegistro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casos",
            name="id_comple_info",
            field=models.OneToOneField(
                blank=True,
                db_column="id_comple_info",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.infocomplementaria",
            ),
        ),
        migrations.AlterField(
            model_name="casos",
            name="id_seguimiento",
            field=models.OneToOneField(
                db_column="id_seguimiento",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.seguimiento",
            ),
        ),
    ]
