# Generated by Django 4.1.2 on 2022-10-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_asignaciontarea_detalle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignaciontarea",
            name="actividad",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
