# Generated by Django 4.1.2 on 2022-10-26 22:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_asignaciontarea_actividad"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignaciontarea",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
