# Generated by Django 4.1.2 on 2022-10-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_asignaciontarea_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignaciontarea",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
    ]
