# Generated by Django 4.1.2 on 2022-10-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_asignaciontarea_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignaciontarea", name="fecha", field=models.DateField(),
        ),
    ]
