# Generated by Django 4.1.2 on 2022-10-28 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_casos_id_comple_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infocomplementaria",
            name="especialidad_med",
            field=models.ForeignKey(
                blank=True,
                db_column="especialidad_med",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.especialidadmed",
            ),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="gestor_farma",
            field=models.ForeignKey(
                blank=True,
                db_column="gestor_farma",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.gestorfarmacia",
            ),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="ips_id_terapia",
            field=models.ForeignKey(
                blank=True,
                db_column="ips_id_terapia",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.ips",
            ),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="terapia",
            field=models.ForeignKey(
                blank=True,
                db_column="terapia",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.terapia",
            ),
        ),
    ]
