# Generated by Django 4.1.2 on 2022-10-28 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_infocomplementaria_especialidad_med_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casos",
            name="id_seguimiento",
            field=models.OneToOneField(
                blank=True,
                db_column="id_seguimiento",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.seguimiento",
            ),
        ),
    ]
