# Generated by Django 4.1.2 on 2022-10-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_casos_id_seguimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infocomplementaria",
            name="fech_rad_aut_farm",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="fecha_aut",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="fecha_entrega",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="fecha_for_medi",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
