# Generated by Django 4.1.2 on 2022-10-28 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_infocomplementaria_fech_rad_for_eps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seguimiento",
            name="descripcion",
            field=models.TextField(default="escriba"),
        ),
        migrations.AlterField(
            model_name="seguimiento",
            name="id_gestor",
            field=models.ForeignKey(
                blank=True,
                db_column="id_gestor",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.gestorcaso",
            ),
        ),
    ]
