# Generated by Django 4.1.2 on 2022-10-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_seguimiento_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignaciontarea",
            name="asginacion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
