# Generated by Django 4.1.2 on 2022-10-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_asignaciontarea_estado_pendiente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignaciontarea",
            name="estado_pendiente",
            field=models.CharField(
                blank=True,
                choices=[("1", "activo"), ("0", "inactivo")],
                default="1",
                max_length=8,
                null=True,
            ),
        ),
    ]
