# Generated by Django 4.1.2 on 2022-10-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_asignaciontarea_estado_pendiente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casos",
            name="adjunto_seg",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="casos",
            name="adjunto_terc",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="casos",
            name="formula_medica",
            field=models.FileField(upload_to=""),
        ),
    ]
