# Generated by Django 4.1.2 on 2022-10-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_casos_adjunto_seg_alter_casos_adjunto_terc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensajescorreo",
            name="para",
            field=models.TextField(blank=True, null=True),
        ),
    ]
