# Generated by Django 4.1.2 on 2022-10-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_mensajescorreo_para"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casos",
            name="adjunto_seg",
            field=models.FileField(upload_to="uploads"),
        ),
        migrations.AlterField(
            model_name="casos",
            name="adjunto_terc",
            field=models.FileField(upload_to="uploads"),
        ),
        migrations.AlterField(
            model_name="casos",
            name="formula_medica",
            field=models.FileField(upload_to="uploads"),
        ),
    ]
