# Generated by Django 4.1.2 on 2022-11-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_alter_casos_adjunto_seg_alter_casos_adjunto_terc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casos",
            name="fechaatenabierto",
            field=models.DateField(db_column="fechaAtenAbierto", null=True),
        ),
        migrations.AlterField(
            model_name="casos",
            name="fechaatencioneps",
            field=models.DateField(db_column="fechaAtencionEps"),
        ),
        migrations.AlterField(
            model_name="casos",
            name="fechaatenfinalizado",
            field=models.DateField(db_column="fechaAtenFinalizado", null=True),
        ),
        migrations.AlterField(
            model_name="casos",
            name="fechaatenproceso",
            field=models.DateField(db_column="fechaAtenProceso", null=True),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="fech_rad_aut_farm",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="fech_rad_for_eps",
            field=models.DateField(blank=True, db_column="fech_rad_for_EPS", null=True),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="fecha_aut",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="fecha_entrega",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="infocomplementaria",
            name="fecha_for_medi",
            field=models.DateField(blank=True, null=True),
        ),
    ]
