# Generated by Django 4.1.2 on 2022-11-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_alter_casos_fechaatenabierto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="especialidadmed",
            name="nombre",
            field=models.CharField(db_column="nombre", max_length=40),
        ),
    ]
