# Generated by Django 4.1.2 on 2022-11-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_alter_especialidadmed_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="especialidadmed",
            name="id_esp",
            field=models.SmallAutoField(
                db_column="id_esp", primary_key=True, serialize=False
            ),
        ),
    ]
