# Generated by Django 4.1.2 on 2022-11-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_especialidadmed_id_esp"),
    ]

    operations = [
        migrations.AddField(
            model_name="datosusuario",
            name="trata_data",
            field=models.CharField(
                choices=[(1, "acepto")], default=None, max_length=5, null=True
            ),
        ),
    ]
