# Generated by Django 4.1.2 on 2022-11-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_alter_datosusuario_trata_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casos",
            name="fecharesgistrocaso",
            field=models.DateField(
                blank=True, db_column="fechaResgistroCaso", null=True
            ),
        ),
    ]
