# Generated by Django 4.1.2 on 2022-11-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alter_casos_fecharesgistrocaso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casos",
            name="fechaatenabierto",
            field=models.DateField(
                db_column="fechaAtenAbierto", default="0000-00-00", null=True
            ),
        ),
        migrations.AlterField(
            model_name="casos",
            name="fechaatenfinalizado",
            field=models.DateField(
                db_column="fechaAtenFinalizado", default="0000-00-00", null=True
            ),
        ),
        migrations.AlterField(
            model_name="casos",
            name="fechaatenproceso",
            field=models.DateField(
                db_column="fechaAtenProceso", default="0000-00-00", null=True
            ),
        ),
        migrations.AlterField(
            model_name="casos",
            name="fecharesgistrocaso",
            field=models.DateField(
                blank=True,
                db_column="fechaResgistroCaso",
                default="0000-00-00",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datosusuario",
            name="trata_data",
            field=models.CharField(
                choices=[
                    (
                        1,
                        "Acepto Términos y condiciones y autorizacion de tratamiento de datos",
                    ),
                    (2, "No aceptar"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
    ]
