# Generated by Django 4.1.2 on 2022-11-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_alter_casos_fechaatenabierto_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="datosusuario", name="trata_data",),
    ]
