# Generated by Django 4.1.2 on 2022-11-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_remove_datosusuario_trata_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignaciontarea",
            name="fech_registro",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="asignaciontarea", name="fecha", field=models.DateField(),
        ),
    ]
