# Generated by Django 4.1.2 on 2022-11-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_alter_casos_fecharesgistrocaso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casos",
            name="fecharesgistrocaso",
            field=models.DateTimeField(
                blank=True, db_column="fechaResgistroCaso", null=True
            ),
        ),
    ]
