# Generated by Django 4.1.2 on 2022-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_alter_casos_fecharesgistrocaso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casos",
            name="fechaatenabierto",
            field=models.DateField(db_column="fechaAtenAbierto", null=True),
        ),
        migrations.AlterField(
            model_name="casos",
            name="fechaatenfinalizado",
            field=models.DateField(db_column="fechaAtenFinalizado", null=True),
        ),
        migrations.AlterField(
            model_name="casos",
            name="fechaatenproceso",
            field=models.DateField(db_column="fechaAtenProceso", null=True),
        ),
    ]
