# Generated by Django 4.1.2 on 2022-11-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_alter_casos_fechaatenabierto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casos",
            name="fecharesgistrocaso",
            field=models.DateField(
                blank=True, db_column="fechaResgistroCaso", null=True
            ),
        ),
    ]
