# Generated by Django 4.1.2 on 2022-11-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_alter_casos_fecharesgistrocaso"),
    ]

    operations = [
        migrations.RemoveField(model_name="asignaciontarea", name="color",),
        migrations.AddField(
            model_name="asignaciontarea",
            name="prioridad",
            field=models.CharField(
                blank=True,
                choices=[("1", "Alta"), ("2", "Media"), ("3", "Baja")],
                default="3",
                max_length=10,
                null=True,
            ),
        ),
    ]
