# Generated by Django 4.1.2 on 2022-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_remove_asignaciontarea_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignaciontarea",
            name="prioridad",
            field=models.CharField(
                blank=True,
                choices=[("Alta", "Alta"), ("Media", "Media"), ("Baja", "Baja")],
                default="Baja",
                max_length=10,
                null=True,
            ),
        ),
    ]
