# Generated by Django 4.1.2 on 2022-11-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_alter_asignaciontarea_prioridad"),
    ]

    operations = [
        migrations.RemoveField(model_name="reportes", name="id_caso",),
        migrations.RemoveField(
            model_name="visualizacioncasohistorial", name="id_usuario",
        ),
        migrations.RemoveField(model_name="visualizacioncasohistorial", name="idcaso",),
        migrations.RemoveField(model_name="analista", name="id_correo",),
        migrations.RemoveField(model_name="gestorcaso", name="id_correo",),
        migrations.RemoveField(model_name="pacienteusuario", name="id_correo",),
        migrations.DeleteModel(name="DatosAnalisis",),
        migrations.DeleteModel(name="MensajesCorreo",),
        migrations.DeleteModel(name="Reportes",),
        migrations.DeleteModel(name="VisualizacionCasoHistorial",),
    ]
