from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(DatosUsuario)
admin.site.register(Pais)
admin.site.register(TipoDocumento)
admin.site.register(Analista)
admin.site.register(AsignacionTarea)
admin.site.register(BarreraAcceso)
admin.site.register(Casos)
admin.site.register(TipoEnfermedad)
admin.site.register(ClasificacionPbs)
admin.site.register(DatosAnalisis)
admin.site.register(Departamento)
admin.site.register(EnvioAlertas)
admin.site.register(Eps)
admin.site.register(EspecialidadMed)
admin.site.register(Estado)
admin.site.register(Genero)
admin.site.register(GestorFarmacia)
admin.site.register(GrupoEtnico)
admin.site.register(IndicadoresGestion)
admin.site.register(InfoComplementaria)
admin.site.register(Ips)
admin.site.register(MensajesCorreo)
admin.site.register(Municipio)
admin.site.register(PoblacionEspecial)
admin.site.register(Regimen)
admin.site.register(GestorCaso)